export const basePersonajes = [
  {
    name: "Priscilla Vargas",
    personId: "priscillavargas",
    image: "/images/avatar/priscilla-avatar.png",
    type: "26",
    card_image: "priscilla-card-image.png",
    notification_id: "b2",
    messages_without_box: [
      "¡La Caja Mágica está cerca! Alguno de nuestros periodistas puede saber más. ¡Búscalos!",
      "Yo escuché rumores… Quizá José Luis sepa algo. ¡Ve a buscarlo!",
      "¿Y si preguntas a alguien más en el set? 😏",
      "La Caja Mágica es tímida… pero aparecerá ¡No te rindas!",
      "Yo siento que viene pronto… qué nervios 😆",
    ],
    messages_with_box: [
      "¡Completaste todos los retos de hoy! Te espero mañana para más sorpresas ;)",
      "¡Hoy estuviste increíble! Te veo mañana para seguir jugando.",
    ],
  },
  {
    name: "José Luis Repentina",
    personId: "joseluisrepentina",
    image: "/images/avatar/jose-luis-avatar.png",
    type: "26",
    notification_id: "n3",
    card_image: "jose-luis-card-image.png",
    messages_without_box: [
      "Yo también estoy buscando la Caja Mágica ¡Pregúntale a alguien más!",
      "Sigue preguntando y la Caja Mágica aparecerá ;)",
      "¿Ya hablaste con algún periodista? Hazlo rápido 😉",
      "¿Ya le preguntaste a Pri? Tiene cara de saber 🤓",
      "Yo buscaría a alguien más… en el set sospechan algo 🤔",
    ],
    messages_with_box: [
      "¡Todo listo por hoy! Las sorpresas siguen mañana.",
      "¡Hoy fuiste imparable! Regresa mañana por más premios.",
    ],
  },
  {
    name: "José Maria Del Pino",
    personId: "josemariadelpino",
    image: "/images/avatar/jose-maria-del-pino.png",
    type: "26",
    card_image: "jose-maria-del-pino-card-image.png",
    messages_without_box: [
      "Ya casi encuentras la Caja Mágica ¡No te rindas!",
      "¡Tienes ojo afilado, yo sé que la ves pronto!",
      "¡Sigue pegado! Ya casi llega el momento 📦",
      "¡No cambies el canal! La Caja Mágica puede llegar...",
      "Yo apostaría que falta poco… pero quién sabe 😅",
    ],
    messages_with_box: [
      "¡Lo hiciste increíble hoy! Ven mañana para más sorpresas 😉",
    ],
  },
  {
    name: "Michelle Adam",
    personId: "michelleadam",
    image: "/images/avatar/michelle-avatar.png",
    type: "26",
    card_image: "michelle-card-image.png",
    messages_without_box: [
      "¡Todos estamos buscando la Caja Mágica! Pregunta por ahí… alguien sabe algo.",
      "No parpadees que se te escapa. ¡Pregunta a alguien más!",
      "Parece que alguien ya la vio… ¡Búscalo!",
      "¡Aún nada! Pero ya casi se deja ver…",
      "La paciencia es tu superpoder hoy 💥 ¡Ya casi!",
    ],
    messages_with_box: ["¡Terminaste los retos! Mañana hay más sorpresas ;)"],
  },
  {
    name: "Delfina Gomez_NON",
    personId: "person_10",
    image: "/images/avatar/michelle-avatar.png",
    type: "26",
    card_image: "michelle-card-image.png",
    messages_without_box: [
      "Esta Caja sí que sabe esconderse 🤣 ¡Sigue buscando!",
      "¡Pregunta sin miedo! Alguien sabe cuándo llega...",
      "Creo que Pri sabe algo… pregúntale 😂",
    ],
    messages_with_box: ["¡Te luciste hoy! Ven mañana por más diversión 😉"],
  },
  {
    name: "Gabriel Alegria_NON",
    personId: "person_11",
    image: "/images/avatar/michelle-avatar.png",
    type: "26",
    card_image: "michelle-card-image.png",
    messages_without_box: [
      "Seguro alguien tiene pista… ¡insiste!",
      "La Caja Mágica es tímida… pero aparecerá ;)",
      "No tengo pistas todavía… ¡tú sigue esperando!",
    ],
    messages_with_box: [
      "¡Lo hiciste increíble! Mañana te espera algo especial 😉",
    ],
  },
  {
    name: "Chef Camila_NON",
    personId: "person_12",
    image: "/images/avatar/michelle-avatar.png",
    type: "26",
    card_image: "michelle-card-image.png",
    messages_without_box: [
      "Seguro alguien tiene pista… ¡insiste!",
      "La Caja Mágica es tímida… pero aparecerá ;)",
      "No tengo pistas todavía… ¡tú sigue esperando!",
    ],
    messages_with_box: ["¡Te luciste hoy! Ven mañana por más diversión 😉"],
  },
  {
    name: "Meli",
    personId: "meli",
    image: "/images/avatar/meli-avatar.png",
    type: "brand",
  },
  {
    name: "Caja",
    personId: "caja",
    image: "/images/avatar/meli-avatar.png",
    card_image: "caja-card-image.png",
    type: "box",
  },
];
