export const notificationsConfig = [
  {
    id: "n2",
    text: "¡Encontraste una camiseta de Millonarios!",
    img: "/images/notifications/jerseyMillonarios.png",
    type: "trigger",
    triggerKey: "jerseyMillonarios",
  },
  {
    id: "n3",
    text: "¡Encontraste una camiseta de Independiente Medellín!",
    img: "/images/notifications/jerseyMedellin.png",
    type: "time",
    triggerKey: "jerseyMedellin",
  },
  {
    id: "n4",
    text: "¡Encontraste una camiseta de Atlético Nacional!",
    img: "/images/notifications/jerseyNacional.png",
    type: "time",
    triggerKey: "jerseyNacional",
  },
  {
    id: "n5",
    text: "¡Aquí está Michelle! Toca arriba y descubre sus recomendados",
    type: "time",
    triggerKey: "michelleadam",
  },
  {
    id: "n6",
    text: "Toca arriba y encuentra las recomendaciones de José María",
    type: "time",
    triggerKey: "josemariadelpino",
  },
  {
    id: "n7",
    text: "¡Encontraste una caja! Descubre el descuento especial",
    type: "time",
    triggerKey: "recogBox",
  },
  {
    id: "n8",
    text: "¡Encontraste un logo! Descubre el descuento especial",
    type: "time",
    triggerKey: "recogLogo",
  },
  {
    id: "n9",
    text: "¡Arquero en pantalla!",
    type: "trigger",
    triggerKey: "sam3_goalkeeper",
  },
  {
    id: "n10",
    text: "¡Árbitro en pantalla!",
    type: "trigger",
    triggerKey: "sam3_referee",
  },
  {
    id: "n11",
    text: "¡Juez de línea con banderín!",
    type: "trigger",
    triggerKey: "sam3_linesman",
  },
  {
    id: "n12",
    text: "¡Banca de suplentes!",
    type: "trigger",
    triggerKey: "sam3_bench",
  },
  {
    id: "n13",
    text: "¡Camilla en campo!",
    type: "trigger",
    triggerKey: "sam3_stretcher",
  },
  {
    id: "n14",
    text: "¡Brazalete de capitán!",
    type: "trigger",
    triggerKey: "sam3_armband",
  },
];
